version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: America/Sao_Paulo
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  user-api:
    restart: on-failure
    build: ./app
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    environment:
      WAIT_HOSTS: mysql:3306
    command: mvn clean spring-boot:run
    depends_on:
      - docker-mysql